### ISSUE TITLE
Bot message for no results found

### ISSUE THREAD

**Issue by ivov** [MLH-Fellowship/0.2.1-fellowbook#20]
From @theycallmeswift 

> The bot could use an error message if it doesn't find someone.

**Comment by shu8** [comment]
I also think it's worth us looking into whether we can use the Discord username to match a Fellow's GitHub profile? It seems more intuitive to say `!gimmer @DiscordUsername` rather than their GitHub username which most people probably won't know at first.

The discord.js library might give us the discord username/nickname - we could map the nickname to the db name's because the discord server rules are that your nickname should be your full name (there will be exceptions of course but it's worth us looking into!)

**Comment by ivov** [comment]
Definitely, I've been looking into this. But we should be careful with the @mention in Discord because the user might not actually want to call the person they are checking out. In any case, @mentions might be better addressed as a standalone issue?

**Comment by shu8** [comment]
Done by @ivov
